### ISSUE TITLE
Update README File

### ISSUE THREAD

**Issue by IshaanAdarsh** [NITRR-Open-Source-Community/OpenSource-Internships#1]
**Description:** Update the README file for the repository. The README should provide an overview of the repository's purpose, how to contribute, and any guidelines for adding internship programs.

**Task:**
- Write an introduction explaining the repository's purpose.
- Include instructions for contributors.

**Labels:** Documentation

**Comment by MasterIfeanyi** [comment]
@IshaanAdarsh please assign this to me.

**Comment by MasterIfeanyi** [comment]
@IshaanAdarsh can you add an hacktoberfest-accepted label.
