### ISSUE TITLE
Add Contributing Guidelines

### ISSUE THREAD

**Issue by IshaanAdarsh** [NITRR-Open-Source-Community/OpenSource-Internships#2]
**Description:** Develop contributing guidelines that detail how contributors can add, edit, or update information about internship programs. These guidelines should ensure consistency in data entry.

**Task:**
- Create a CONTRIBUTING.md file.
- Define the process for adding internship programs.
- Specify data format and any required fields.

**Labels:** Documentation, Guidelines

**Comment by sahalhes** [comment]
Hey I am a beginner in open source contribution, I feel this can be a good start for me.
Could you please assign me this

**Comment by sahalhes** [comment]
@IshaanAdarsh I did PR after creating CONTRIBUTING.md file. Please review it and tell if any changes are required.
Also please give some advice to me as this is my first pull request.
