### ISSUE TITLE
Collect Initial Internship Programs

### ISSUE THREAD

**Issue by IshaanAdarsh** [NITRR-Open-Source-Community/OpenSource-Internships#3]
**Description:** Start populating the repository by adding information about open source internship programs. This can include the program name, description, application details, and deadlines.

**Task:**
- Research and gather information on open source internship programs.
- Create individual files or entries for each program.
- Include program name, description, application details, and deadlines.

**Labels:** Data Entry

**Comment by Arnav17Sharma** [comment]
@IshaanAdarsh please assign this to me.

**Comment by Arnav17Sharma** [comment]
@IshaanAdarsh
I prepared a detailed analysis of a single program (MLH Fellowship Program) on my forked repo. Please check it out and suggest changes(if any) so that I implement those changes while adding new programs as well. 
Forked Repo : https://github.com/Arnav17Sharma/OpenSource-Internships

Also, how many programs should be added to the list?

**Comment by IshaanAdarsh** [comment]
@Arnav17Sharma good going. 

Make short intros and links to websites for the Readme.md but create proper folder for the details description of the programmes. Add a logo too if possible, just the maximum basic information someone can get from the main readme.

Something like Programs/MLH/MLH.md is good 
Also if you are talking content from somewhere, at the bottom link the sources too (just a good practice)

**Comment by Arnav17Sharma** [comment]
@IshaanAdarsh 
I added the sources and somme additional information in the main README.md 
https://github.com/Arnav17Sharma/OpenSource-Internships
Does this look fine ?
I am going to add more programs going forward.
